webtalk_init -webtalk_dir F:/vivado_project/RISCV_vivado_20250403/RISCV_vivado_20250403.sim/sim_1/behav/xsim/xsim.dir/riscv_soc_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Apr  8 16:20:36 2025" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "f0c88b87-d0b8-49db-b311-eccb817e56a0" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "3ebe628960034ca7aeb972937bcf6d47" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "138" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2496 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "9190 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.01_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "9276_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1644640846 -regid "" -xml F:/vivado_project/RISCV_vivado_20250403/RISCV_vivado_20250403.sim/sim_1/behav/xsim/xsim.dir/riscv_soc_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html F:/vivado_project/RISCV_vivado_20250403/RISCV_vivado_20250403.sim/sim_1/behav/xsim/xsim.dir/riscv_soc_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm F:/vivado_project/RISCV_vivado_20250403/RISCV_vivado_20250403.sim/sim_1/behav/xsim/xsim.dir/riscv_soc_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
